---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="7"
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: JkxLhjzWWPJdWJx0ipXriZtzXyFjzPGFDwn3TUEsk92a/U1AcOlh0xBs3p0N9peanZPofM/rQPv48vYeMnPNTSsZ6GXbOnYLT/y/dthe91CN1tqYo3m7PxmC/gRrnssw+cvXAb/DeDtaz+c/6CEL0g7RYAuxD17XbHPz2KCOeEd0u9eGdAl3zxLiIlww6lLzRL/DjY97ZoH1dXxrDaM3pz65FznCtgS5skVrDpGy7tCxhY3EjBH+vlo5QMAoJokRKV9cfKeXbPKwDzOp7lSZD1Bih2SmCUSA80Ch++/Y8i7ANykGmT/CbLjIgFiByIEP295tGgnbWqY26pwTP+3A6w2Gcyq/MOIynAYPJcadAQBeNUKqS9ql5CBtmNfONlTy3ZIJ2tPMvYF7LsbQr+eTnaiddVKas7QeIwORsXJh8sT5T1HpTpar5CZAq9mIL9VlHGZoLi+Bo8cy5b841xxjxG/TeneC6MmT42z5YerUdXA+/7lKpwlLx2TmrKGBGlqKnP3AuQvNrynACQOHhmN20AuAMfiY8HCEKm9adyB55UIsUXXVJBFm0wXjLk2MJ068+L6qnZhR4xAZD2cloCzCCSWUL420H+OiXTQf4Kn3HDlRKJEGk2ZrAZg6LOrNAwAkupMa0DSRqa9q5oC1zN0oVj5L6cBSlUfdG9KoF7zP0oI=
  email: false
