---
# tasks file for tigervnc
- name: install software
  package:
    name: "{{ tigervnc_packages }}"
    state: present
  register: tigervnc_install_software
  until: tigervnc_install_software is succeeded
  retries: 3

- name: generate vnc password
  shell: set -o pipefail ; printf "{{ tigervnc_password }}\n{{ tigervnc_password }}\n" | vncpasswd
  args:
    creates: /home/{{ tigervnc_username }}/.vnc/passwd
  become: yes
  become_user: "{{ tigervnc_username }}"

- name: place service unit
  template:
    src: vncserver.service.j2
    dest: /etc/systemd/system/vncserver-{{ tigervnc_username }}@.service
  notify:
    - systemctl daemon-reload

- name: start software
  service:
    name: "{{ tigervnc_service }}"
    state: started
    enabled: yes
