---
# handlers file for tigervnc
- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: restart tigervnc-server
  service:
    name: "{{ tigervnc_service }}"
    state: restarted

