---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.epel
    - role: robertdebock.hostname
    - role: robertdebock.users
      users_group_list:
        - name: vncgroup
      users_user_list:
        - name: vncuser
          group: vncgroup
