---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: check if connection still works
      ping:

    - name: test port 5901
      wait_for:
        port: 5901

    - name: show testing instruction
      debug:
        msg: "Please run: vncviewer {{ ansible_default_ipv4.address }}:5901"
